name: debug_log_console
description: Using a draggable and hoverable panel to display the key info/log of app state, network requests, etc. The info/log can be copied or shared as file. 
repository: https://github.com/malikwang/debug_log_console
homepage: https://github.com/malikwang/debug_log_console

version: 1.1.0

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  share_extend:
  path_provider:

dev_dependencies:
  flutter_test:
    sdk: flutter
